---
title: "Homophily-Functions"
author: "Emily Coco"
date: "7/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(grDevices)
require(hhi)
require(data.table)
library(networkD3)
library(webshot)
library(rmarkdown)

```

####HHI function
0 is heterophilious
1 is homophilious

sum of the market shares of groups
```{r hhi}
get.hhi <- function(nodes, edges, column) {
  results <- as.data.frame(unique(nodes$id))
  results$hhi <- NULL
  for(i in unique(nodes$id)) {
    cur.edges <- edges[edges$from == i,]
    cur.edges <- cur.edges[-1]
    colnames(cur.edges) <- c("from", "id", "rel","color", "dir")
    cur.edges <- left_join(cur.edges, nodes, by = "id")
    
    if(!is.null(dim(cur.edges))) {
      shares <- as.data.frame(table(cur.edges[,column]))[as.data.frame(table(cur.edges[,column]))$Freq != 0, ]
      shares$prop <- shares$Freq/sum(shares$Freq)
      results$hhi[i] <- hhi(shares, "prop")
    }
  }
  return(results)
}
```


####Krackhardt and Stern E-I Index
-1 is homophilious
1 is heterophilious

function:
number of ties in different groups - number of ties in same group/ number of total ties

```{r similarity}
get.ei <- function(nodes, edges, column) {
  results <- as.data.frame(unique(nodes$id))
  results$ei <- 0
  for(i in unique(nodes$id)) {
    cur.edges <- edges[edges$from == i,]
    cur.edges <- cur.edges[-1]
    colnames(cur.edges) <- c("from", "id", "rel","color", "dir")
    cur.edges <- left_join(cur.edges, nodes, by = "id")
    
    if(!is.null(dim(cur.edges))) {
      check <- as.character(nodes[nodes$id == i, column])
      num.same <- nrow(cur.edges[cur.edges[,column] == check,])
      num.dif <- nrow(cur.edges[cur.edges[,column] != check,])
      results$ei[i] <- as.numeric((num.same - num.dif)/nrow(cur.edges))
    }
  }
  return(results)
}

```
