---
title: "R Notebook"
author: "Dakota Murray"
output: html_notebook
---

```{r}
library(tidyverse)
library(ACSSS)
theme_set(theme_bw())
```


```{r read_data, echo=FALSE}
path <- '~/Documents/Analyzing-CSSS/data/raw/cleaned_csss-all.csv'
dat <- read.csv(path)

# Load an iteration node and edge file
node_path <- "~/Documents/Analyzing-CSSS/data/derived/nodefiles/2017.SantaFe_nodes.csv"
nodes <- read.csv(node_path) %>%
  #mutate(id = paste0("", id)) %>%
  select(-X)

edge_path <- "~/Documents/Analyzing-CSSS/data/derived/edgefiles/2017.SantaFe_edges.csv"
edges <- read.csv(edge_path) %>%
  select(-X)

head(nodes)
head(edges)
```

The first thing that we want to do is save the actual count of the metric we are using. here, we will use the very simple metric of "number of different-gender connections between participants"
```{r}
nodes.only.gender <- nodes %>% select(id, gender) %>% mutate(gender = ifelse(is.na(gender), "UNK", gender))
dist <- sapply(c(1:10), function(x) {
  
  nodes.only.gender$gender <- nodes.only.gender$gender[sample(nrow(nodes.only.gender))]

  edges.gender <- edges %>%
    left_join(nodes.only.gender, by = c("from" = "id")) %>%
    left_join(nodes.only.gender, by = c("to" = "id"), suffix = c(".from", ".to"))
  
  #return(sum(edges.gender$gender.from != edges.gender$gender.to, na.rm = T))
  return(mean(get_ei(nodes.only.gender, edges, "gender")$ei, na.rm = T))
})

hist(dist)
```

```{r}
mean(get_ei(nodes, edges, "gender")$ei, na.rm = T)

```

```{r}
#node-measures
node_measures <- function(graph) {
  nodes <- DiagrammeR::get_node_df(graph)
  results <- nodes %>%
    left_join(get_degree_total(graph), by = "id") %>%
    left_join(get_betweenness(graph), by = "id") %>%
    left_join(get_eigen_centrality(graph), by = "id") %>%
    left_join(get_constraint(graph), by = "id")
  
  results$discp_hmph <- NULL
  results$pos_hmph <- NULL
  results$cntry_hmph <- NULL
  
  #attempting to get homophily measures --need to add gender homophily, and prestige homophily
  edges <- DiagrammeR::get_edge_df(graph)
  for(i in unique(nodes$id)) {
    cur.edges <- edges[edges$from == i,]
    cur.edges <- cur.edges[-1]
    colnames(cur.edges) <- c("from", "id", "rel", "color", "dir")
    cur.edges <- left_join(cur.edges, nodes, by = "id")
    if(!is.null(dim(cur.edges))) {
      discp.shares <- as.data.frame(table(cur.edges$discp))[as.data.frame(table(cur.edges$discp))$Freq != 0, ]
      discp.shares$prop <- discp.shares$Freq/sum(discp.shares$Freq)
      results$discp_hmph[results$id == i] <- hhi(discp.shares, "prop")
      
      pos.shares <- as.data.frame(table(cur.edges$pos.var))[as.data.frame(table(cur.edges$pos.var))$Freq != 0, ]
      pos.shares$prop <- pos.shares$Freq/sum(pos.shares$Freq)
      results$pos_hmph[results$id == i] <- hhi(pos.shares, "prop")
      
      cntry.shares <- as.data.frame(table(cur.edges$cntry))[as.data.frame(table(cur.edges$cntry))$Freq != 0, ]
      cntry.shares$prop <- cntry.shares$Freq/sum(cntry.shares$Freq)
      results$cntry_hmph[results$id == i] <- hhi(cntry.shares, "prop")
      
      prstg.shares <- as.data.frame(table(cur.edges$prstg))[as.data.frame(table(cur.edges$prstg))$Freq != 0, ]
      prstg.shares$prop <- prstg.shares$Freq/sum(prstg.shares$Freq)
      results$prstg_hmph[results$id == i] <- hhi(prstg.shares, "prop")
      
      gen.shares <- as.data.frame(table(cur.edges$gender))[as.data.frame(table(cur.edges$gender))$Freq != 0, ]
      gen.shares$prop <- gen.shares$Freq/sum(gen.shares$Freq)
      results$gender_hmph[results$id == i] <- hhi(gen.shares, "prop")
    }
  }
  
  return(results)
}

graph.with.measures <- node_measures(graph)

mean(graph.with.measures$gender_hmph)
#graph.with.measures
```

First, lets get the actual gender scores for each year/place of the summer school
```{r message=FALSE, warning=FALSE}
iters <- unique(no.2011$iteration)
actual_discp_hmph <- sapply(iters, function(y) {
  node.df <- build_node_dataframe(df, iter = y)
  edge.df <- build_edge_dataframe(df, iter = y)
  graph <- create_graph(nodes_df = node.df, 
                      edges_df = edge.df)

  measures <- node_measures(graph)
  
  return(mean(measures$discp_hmph))
})

actual_df <- data.frame(year = iters, discp_hmph = actual_discp_hmph)
```


Now lets try generating a distribution of random values
```{r message=FALSE, warning=FALSE}
y <- "2018.Santa Fe"
distribution <- sapply(1:500, function(x) {
  node.df <- build_node_dataframe(df, iter = y)
  node.df$discp <- factor(sample(node.df$discp))
  edge.df <- build_edge_dataframe(df, iter = y)
  graph <- create_graph(
                      nodes_df = node.df, 
                      edges_df = edge.df)

  measures <- node_measures(graph)
  
  return(mean(measures$discp_hmph))
})

distribution = matrix(distribution, ncol = 1)

as.data.frame(distribution) %>%
  ggplot(aes(x = V1)) +
  geom_histogram(bins = 40, alpha = 0.8, color = "black") +
  geom_vline(xintercept = 0.445, color = "dodgerblue", size = 1.5, alpha = 0.8) +
  theme_minimal() +
  labs(
    title = "2018 Null Model vs. Actual Disciplinary Homophily",
    x = "Average Disciplinary Node Homophily") +
  geom_text(x = 0.45, y = 31, label = "actual")

ggsave("~/Desktop/csss_null_model_discipline.png", height = 9, width = 9)
```
